app/__init__.py
from flask import Flask
from config import Config
from .site.routes import site
from .authentication.routes import auth
from .api.routes import api

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from models import db as root_db, login_manager, ma
from flask_cors import CORS
from helpers import JSONEncoder

app = Flask(__name__)
CORS(app)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)

app.json_encoder = JSONEncoder
app.config.from_object(Config)
root_db.init_app(app)
login_manager.init_app(app)
ma.init_app(app)
migrate = Migrate(app, root_db)

app/api/routes.py
from flask import Blueprint, request, jsonify, render_template, flash, url_for, redirect
from flask_login import login_user, logout_user, LoginManager, current_user, login_required
from helpers import token_required
from models import db, User, CarCollection
from forms import CarCreationForm
from models import car_schema, cars_schema

api = Blueprint('api', __name__, url_prefix='/api', template_folder='api_templates')

@api.route('/createCar', methods = ['GET', 'POST'])
def create_car():
    form = CarCreationForm()
    make = form.make.data
    model = form.model.data
    year = form.year.data
    user_token = form.user_token.data

    logged_user = User.query.filter(User.token == user_token).first()
    try:
        if logged_user and request.method == 'POST' and form.validate_on_submit():
            car = CarCollection(make, model, year, user_token)

            db.session.add(car)
            db.session.commit()

            print('Car has been added to the database.')
            return redirect(url_for('site.profile'))
        else:
            print('We were not able to add your car to the database.')
    except:
        raise Exception('Invalid form data')

    return render_template('carCreation.html', form=form)

@api.route('/showCars', methods=['GET'])
@login_required
def showCars():
    user_token = current_user.token
    cars = CarCollection.query.filter_by(user_token = user_token).all()

    response = cars_schema.dump(cars)
    return render_template('carTable.html', data=response)

@api.route('/create', methods=['POST'])
@token_required
def create(current_user_token):
    make = request.json['make']
    model = request.json['model']
    year = request.json['year']
    car = CarCollection(make, model, year, current_user_token.token)

    db.session.add(car)
    db.session.commit()

    response = car_schema.dump(car)
    return jsonify(response)

@api.route('/getCars', methods=['GET'])
@token_required
def getCars(current_user_token):
    a_user = current_user_token.token
    cars = CarCollection.query.filter_by(user_token=a_user).all()
    response = cars_schema.dump(cars)
    return jsonify(response)

@api.route('/getCar/<id>', methods=['GET'])
@token_required
def getCar(current_user_token, id):
    car = CarCollection.query.get(id)
    response = car_schema.dump(car)
    return jsonify(response)

@api.route('/updateCar/<id>', methods=['PUT'])
@token_required
def updateCar(current_user_token, id):
    car = CarCollection.query.get(id)
    car.make = request.json['make']
    car.model = request.json['model']
    car.year = request.json['year']

    db.session.commit()

    response = car_schema.dump(car)
    return jsonify(response)


@api.route('/deleteCar/<id>', methods=['DELETE'])
@token_required
def deleteCar(current_user_token, id):
    car = CarCollection.query.get(id)

    db.session.delete(car)
    db.session.commit()

    response = car_schema.dump(car)
    return jsonify(response)

app/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from forms import UserSignupForm, UserLoginForm
from models import User, db, check_password_hash
from flask_login import login_user, logout_user, LoginManager, current_user, login_required
from werkzeug.security import generate_password_hash, check_password_hash

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    try:
        if request.method == 'POST':
            first_name = request.json['first']
            last_name = request.json['last']
            email = request.json['email']
            username = request.json['username']
            password = request.json['password']

            user = User(first_name, last_name, email, username, password)

            db.session.add(user)
            db.session.commit()

            print('successfully added user')
            
            return jsonify({
                "token": user.token
            })
        else:
            return jsonify({
                "error": "Couldn't create account"
            }, 401)
    except:
        raise Exception('Invalid form data: Please check your form')
    
    # return render_template('signup.html')

@auth.route('/signin', methods=['GET', 'POST'])
def signin():
    try:
        if request.method == 'POST':
            username = request.json["username"]
            password = request.json["password"]

            logged_user = User.query.filter(User.username == username).first()
            if logged_user and check_password_hash(logged_user.password, password):
                # login_user(logged_user)
                # print('logged in')
                return jsonify({
                    "token": logged_user.token
                }) 
            else:
                return jsonify({
                    "error": "No user in Database"
                }, 401)
    except:
        raise Exception('Invalid form data: Please check your form')
    
    # return render_template('signin.html')

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('site.home'))

app/site/routes.py
from flask import Blueprint, render_template

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('home.html')

@site.route('/profile')
def profile():
    return render_template('profile.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Car Inventory</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/a23117853d.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="../static/style.css">
</head>
<body>
    <!-- Navbar -->
    <div>
        <nav class="navbar navbar-expand-lg bg-dark">
            <a class="navbar-brand text-light pl-5" href="{{ url_for('site.home') }}">Car Inventory</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="dark-blue-text"><i
                class="fas fa-bars fa-1x icons"></i></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto order-0">
                    <li class="nav-item">
                        <a href="{{ url_for('site.home') }}" class="nav-link text-light pr-5">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('site.profile') }}" class="nav-link text-light pr-5">Profile</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{{ url_for('auth.logout') }}" class="nav-link text-light pr-5">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signin') }}" class="nav-link text-light pr-5">Sign-In</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signup') }}" class="nav-link text-light pr-5">Sign-Up</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </div>
    <!-- Background -->
    <section>
        <div>
            <img src="../../static/alex-suprun-A53o1drQS2k-unsplash.jpg" class="background" alt="classic cars lined up">
        </div>
    </section>
    {% block content %}
    {% endblock %}
</body>
</html>